version: '3.7'

services:
  web:
    container_name: oauth2_nestjs
    build: docker/dev
    ports:
      - "3333:3333"
      - "7001:7001"
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - postgres

  postgres:
    container_name: oauth2_postgres
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_DB=oauth2_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    container_name: oauth2_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: oauth2_development
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./.data/mongodb:/data/db
