version: '3'

services:
  web:
    container_name: nestjs
    build: docker/dev
    ports:
      - "3333:3333"
      - "7001:7001"
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - database

  database:
    container_name: database
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_DB=oauth2_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
